#!/usr/bin/perl
srand;
rand($.) < 1 && ($line = $_) while <DATA>;
print $line;
__DATA__
/usr/src/linux-headers-2.6.32-31-generic/scripts/pnmtologo.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/libfdt/fdt_wip.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/libfdt/fdt_sw.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/libfdt/fdt_rw.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/libfdt/fdt_strerror.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/libfdt/fdt.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/libfdt/fdt_ro.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/treesource.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/data.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/dtc.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/livetree.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/flattree.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/checks.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/fstree.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/dtc/srcpos.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kallsyms.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/basic/hash.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/basic/fixdep.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/basic/docproc.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/conmakehash.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/mod/sumversion.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/mod/empty.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/mod/modpost.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/mod/mk_elfconfig.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/mod/file2alias.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/selinux/mdp/mdp.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/binoffset.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/genksyms/keywords.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/genksyms/lex.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/genksyms/parse.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/genksyms/genksyms.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/bin2c.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/unifdef.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/lxdialog/util.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/lxdialog/yesno.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/lxdialog/inputbox.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/lxdialog/menubox.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/lxdialog/textbox.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/lxdialog/checklist.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/kconfig_load.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/kxgettext.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/util.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/mconf.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/menu.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/symbol.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/zconf.hash.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/images.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/lex.zconf.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/gconf.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/conf.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/zconf.tab.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/expr.c
/usr/src/linux-headers-2.6.32-31-generic/scripts/kconfig/confdata.c
